
spring:

  application:
    name: service-acl

  # 配置数据源
  datasource:

    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_cloud_security
      username: root
      password: 20010713





  # 关于redis
  redis:
    host: "127.0.0.1"
    port: 6379
    password: "123456"
    jedis:
      pool:
        # 连接池开关
        enabled: true
        # 在给定时间可以分配的最大连接数
        max-active: 8
        #池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接。
        max-idle:  8
        # 当池耗尽时，连接分配在抛出异常之前应该阻塞的最长时间
        max-wait: 2000


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  cloud:
    nacos:
      discovery:
        # nacos 服务端地址
        server-addr: localhost:8848
        # 配置集群名称，也就是机房位置
        #cluster-name: HZ
        # namespace: 5544c4b1-2899-4915-94af-f9940c01c2b9
        # 是否为临时实例，true为临时实例
        ephemeral: false



ribbon:
  eager-load:
    # 开启饥饿加载
    enabled: true





# 开启debug模式，输出调试信息，常用于检查系统运行状况
#debug: true

# 设置日志级别，root表示根节点，即整体应用日志级别
logging:
 # 日志输出到文件的文件名
  file:
    name: server_acl.log
    path: ./logs

  # 设置日志组
  group:
  # 自定义组名，设置当前组中所包含的包
    mao_pro: mao
  level:
    root: info
    # 为对应组设置日志级别
    mao_pro: debug
    # 日志输出格式


server:
  port: 8084


